# Generated by Django 2.1.5 on 2019-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0004_auto_20181008_0214"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingapilookup",
            name="from_lang",
            field=models.CharField(default="zh-Hans", max_length=20),
        ),
        migrations.AddField(
            model_name="bingapilookup",
            name="to_lang",
            field=models.CharField(default="en", max_length=20),
        ),
        migrations.AddField(
            model_name="bingapitranslation",
            name="from_lang",
            field=models.CharField(default="zh-Hans", max_length=20),
        ),
        migrations.AddField(
            model_name="bingapitranslation",
            name="to_lang",
            field=models.CharField(default="en", max_length=20),
        ),
        migrations.AddField(
            model_name="bingapitransliteration",
            name="from_lang",
            field=models.CharField(default="zh-Hans", max_length=20),
        ),
        migrations.AddField(
            model_name="bingapitransliteration",
            name="to_lang",
            field=models.CharField(default="en", max_length=20),
        ),
    ]
