# Generated by Django 2.2.8 on 2020-01-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0008_auto_20200110_0244"),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name="bingapilookup",
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="bingapitranslation",
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="bingapitransliteration",
            index_together=set(),
        ),
    ]
