# Generated by Django 3.1.4 on 2020-12-24 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0010_auto_20200110_0254"),
    ]

    operations = [
        migrations.AddField(
            model_name="bingapilookup",
            name="cached_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bingapitranslation",
            name="cached_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="bingapitransliteration",
            name="cached_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CachedDefinition",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_text", models.CharField(db_index=True, max_length=2000)),
                ("response_json", models.CharField(max_length=25000)),
                ("cached_date", models.DateTimeField(auto_now=True)),
                ("from_lang", models.CharField(db_index=True, default="zh-Hans", max_length=20)),
                ("to_lang", models.CharField(db_index=True, default="en", max_length=20)),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enrich.bingapilookup")),
            ],
        ),
        migrations.AddConstraint(
            model_name="cacheddefinition",
            constraint=models.UniqueConstraint(
                fields=("source_text", "from_lang", "to_lang"), name="unique_trans_cdef"
            ),
        ),
    ]
