# Generated by Django 3.1.4 on 2020-12-26 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0011_auto_20201224_0102"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cacheddefinition",
            index=models.Index(fields=["cached_date", "from_lang", "to_lang"], name="enrich_cach_cached__6fe42c_idx"),
        ),
    ]
