image: python:3.8-slim

variables:
  POSTGRES_DATABASE: tc_db
  POSTGRES_USER: tc_user
  POSTGRES_PASSWORD: tc_pass
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432

  TC_POSTGRES_DB: tc_db
  TC_POSTGRES_USER: tc_user
  TC_POSTGRES_PASSWORD: tc_pass
  TC_POSTGRES_HOST: db
  TC_POSTGRES_PORT: 5432
  TC_DJANKISERV_USERDB_NAME: tc_db
  TC_DJANKISERV_USERDB_USER: tc_user
  TC_DJANKISERV_USERDB_PASSWORD: tc_pass
  TC_DJANKISERV_USERDB_HOST: db
  TC_DJANKISERV_USERDB_PORT: 5432

  TRANSCROBES_ZH_CORENLP_HOST: localhost:9000
  TRANSCROBES_ZH_EN_ABC_DICT_PATH: tests/assets/zhhans_en/zh_en_abc_dict.test.txt
  DJANGO_SETTINGS_MODULE: 'transcrobes.settings'
  TRANSCROBES_ZH_EN_ABC_DICT_INMEM: 'true'
  TRANSCROBES_ZH_EN_CEDICT_PATH: tests/assets/zhhans_en/zh_en_cedict.test.txt
  TRANSCROBES_ZH_EN_CEDICT_INMEM: 'true'
  TRANSCROBES_ZH_HSK_LISTS_PATH: 'tests/assets/enrichers/zh_hsk{}.txt'
  TRANSCROBES_ZH_HSK_LISTS_INMEM: 'true'
  TRANSCROBES_ZH_SUBTLEX_FREQ_PATH: tests/assets/enrichers/zh_subtlex.utf8.test.txt
  TRANSCROBES_ZH_SUBTLEX_FREQ_INMEM: 'true'

  PYTHONDONTWRITEBYTECODE: 1
  GIT_SUBMODULE_STRATEGY: recursive
  APP_PATH: /app
  EXT_REG_BASE: ${EXT_REG_REGISTRY}/${EXT_REG_ORGANISATION}/${CI_PROJECT_NAME}
  TRANSCROBES_DOCKER_REPO: ${EXT_REG_REGISTRY}/${EXT_REG_ORGANISATION}

cache:
  paths:
    - ~/.cache/pip/

stages:
  - test
  - release

test:
  stage: test
  services:
    - name: postgres:12
      alias: db

  before_script:
    - apt update && apt install -y gcc git libmariadb-dev && apt -y autoremove && apt -y clean && rm -rf /var/lib/apt/lists/*
    - pip install -r src/requirements.ci.txt

  variables:
    DATABASE_URL: "postgresql://$TC_POSTGRES_USER:$TC_POSTGRES_PASSWORD@postgres:5432/$TC_POSTGRES_DB"

  script:
    - ./scripts/runtests.sh
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - build
    expire_in: 30 days

release:
  stage: release
  image: transcrobes/tcbuild:0.0.1
  services:
   - docker:dind

  script:
    - pip install -r src/requirements.txt
    - export DOCKER_HOST=tcp://docker:2375/
    - docker login -u ${EXT_REG_USER} -p ${EXT_REG_PASSWORD} ${EXT_REG_REGISTRY}
    - npm install
    - sh scripts/buildimages.sh
  only:
    - master
    - tags
