# Generated by Django 2.1.7 on 2019-02-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0005_auto_20190215_0530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bingapilookup",
            name="from_lang",
            field=models.CharField(db_index=True, default="zh-Hans", max_length=20),
        ),
        migrations.AlterField(
            model_name="bingapilookup",
            name="to_lang",
            field=models.CharField(db_index=True, default="en", max_length=20),
        ),
        migrations.AlterField(
            model_name="bingapitranslation",
            name="from_lang",
            field=models.CharField(db_index=True, default="zh-Hans", max_length=20),
        ),
        migrations.AlterField(
            model_name="bingapitranslation",
            name="to_lang",
            field=models.CharField(db_index=True, default="en", max_length=20),
        ),
        migrations.AlterField(
            model_name="bingapitransliteration",
            name="from_lang",
            field=models.CharField(db_index=True, default="zh-Hans", max_length=20),
        ),
        migrations.AlterField(
            model_name="bingapitransliteration",
            name="to_lang",
            field=models.CharField(db_index=True, default="en", max_length=20),
        ),
    ]
