# Generated by Django 2.1.7 on 2019-02-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0006_auto_20190222_0333"),
    ]

    operations = [
        migrations.AlterIndexTogether(name="bingapilookup", index_together={("source_text", "from_lang", "to_lang")},),
        migrations.AlterIndexTogether(
            name="bingapitranslation", index_together={("source_text", "from_lang", "to_lang")},
        ),
        migrations.AlterIndexTogether(
            name="bingapitransliteration", index_together={("source_text", "from_lang", "to_lang")},
        ),
    ]
