# Generated by Django 2.2.8 on 2020-01-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0007_auto_20190224_0536"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="bingapilookup",
            constraint=models.UniqueConstraint(fields=("source_text", "from_lang", "to_lang"), name="unique_trans"),
        ),
    ]
