# Generated by Django 2.1.7 on 2019-02-24 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zhhans_en', '0002_hsklookup_subtlexlookup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HSKLookup',
        ),
        migrations.DeleteModel(
            name='SubtlexLookup',
        ),
    ]
