# Generated by Django 3.0.8 on 2020-07-05 14:17
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("data", "0001_initial"),
        ("data", "0002_auto_20191218_0933"),
        ("data", "0003_auto_20191218_0935"),
        ("data", "0004_auto_20191218_0948"),
        ("data", "0005_auto_20191218_1226"),
        ("data", "0006_auto_20191222_0611"),
        ("data", "0007_auto_20191222_0926"),
        ("data", "0008_auto_20191223_0438"),
        ("data", "0009_grammarrule_structure"),
        ("data", "0010_auto_20191226_1353"),
        ("data", "0011_auto_20191228_0526"),
        ("data", "0012_auto_20191228_0529"),
        ("data", "0013_auto_20191228_0827"),
        ("data", "0014_auto_20191230_0144"),
        ("data", "0015_auto_20191230_0458"),
        ("data", "0016_auto_20191230_1252"),
        ("data", "0017_usersentenceevaluation"),
        ("data", "0018_sentence_words"),
        ("data", "0019_sentencewords"),
        ("data", "0020_remove_sentence_words"),
        ("data", "0021_auto_20200110_0456"),
        ("data", "0022_userword_is_known"),
        ("data", "0023_auto_20200116_1539"),
    ]

    initial = True

    dependencies = [
        ("enrich", "0007_auto_20190224_0536"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GrammarRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=1000)),
                ("rule", models.CharField(max_length=1000)),
                ("hsk_id", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("sub_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserGrammarRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_known", models.BooleanField()),
                ("grammar_rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.GrammarRule")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SourceText",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=25000)),
                ("text_source_id", models.CharField(max_length=100)),
                ("grammar_rules", models.ManyToManyField(to="data.GrammarRule")),
                ("source", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.Source")),
                ("vocab_levels", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name="usergrammarrule",
            constraint=models.UniqueConstraint(fields=("user", "grammar_rule"), name="user_answer"),
        ),
        migrations.AlterModelOptions(
            name="sourcetext",
            options={"verbose_name": "source_text", "verbose_name_plural": "source_texts"},
        ),
        migrations.CreateModel(
            name="Sentence",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField()),
                ("content", models.TextField()),
                ("parse", models.TextField()),
                ("vocab1", models.IntegerField()),
                ("vocab2", models.IntegerField()),
                ("vocab3", models.IntegerField()),
                ("vocab4", models.IntegerField()),
                ("vocab5", models.IntegerField()),
                ("vocab6", models.IntegerField()),
                ("vocab7", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="SText",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_subid", models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="usergrammarrule",
            name="user_answer",
        ),
        migrations.AddField(
            model_name="grammarrule",
            name="hsk_sub_id",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="grammarrule",
            name="topic_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="source",
            name="sub_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name="usergrammarrule",
            constraint=models.UniqueConstraint(fields=("user", "grammar_rule"), name="user_rule"),
        ),
        migrations.AddField(
            model_name="stext",
            name="source",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.Source"),
        ),
        migrations.AddField(
            model_name="sentence",
            name="grammar_rules",
            field=models.ManyToManyField(to="data.GrammarRule"),
        ),
        migrations.AddField(
            model_name="sentence",
            name="text",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.SText"),
        ),
        migrations.RenameField(
            model_name="sentence",
            old_name="order",
            new_name="sorder",
        ),
        migrations.AlterModelOptions(
            name="sourcetext",
            options={},
        ),
        migrations.CreateModel(
            name="UserTextEvaluation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("difficulty", models.IntegerField(choices=[(-1, "Easy"), (0, "Just right"), (1, "Hard")], default=0)),
                ("text", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.SText")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="grammarrule",
            name="help_url",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="nb_checked",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="nb_seen",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="nb_studied",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usergrammarrule",
            name="is_known",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="last_checked",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="last_studied",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="UserWord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nb_seen", models.IntegerField(default=0)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("nb_checked", models.IntegerField(default=0)),
                ("last_checked", models.DateTimeField(default=django.utils.timezone.now)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enrich.BingAPILookup")),
            ],
        ),
        migrations.AddConstraint(
            model_name="userword",
            constraint=models.UniqueConstraint(fields=("user", "word"), name="user_word"),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="nb_seen_since_last_check",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usergrammarrule",
            name="nb_seen_since_last_study",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usertextevaluation",
            name="date_read",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userword",
            name="nb_seen_since_last_check",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="usergrammarrule",
            name="last_checked",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="usergrammarrule",
            name="last_studied",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="userword",
            name="last_checked",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="usertextevaluation",
            name="difficulty",
            field=models.IntegerField(
                choices=[(-2, "Very easy"), (-1, "Easy"), (0, "Just right"), (1, "Hard"), (2, "Very hard")], default=0
            ),
        ),
        migrations.CreateModel(
            name="UserSentenceEvaluation",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[(-2, "Very easy"), (-1, "Easy"), (0, "Just right"), (1, "Hard"), (2, "Very hard")],
                        default=0,
                    ),
                ),
                ("date_read", models.DateTimeField(default=django.utils.timezone.now)),
                ("sentence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.Sentence")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="SentenceWords",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("index", models.IntegerField()),
                ("pos", models.CharField(max_length=3)),
                ("sentence", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.Sentence")),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enrich.BingAPILookup")),
            ],
        ),
        migrations.AddConstraint(
            model_name="sentencewords",
            constraint=models.UniqueConstraint(fields=("sentence", "word", "index", "pos"), name="sentence_word"),
        ),
        migrations.AddField(
            model_name="userword",
            name="is_known",
            field=models.BooleanField(null=True),
        ),
        migrations.AddConstraint(
            model_name="grammarrule",
            constraint=models.UniqueConstraint(fields=("hsk_id", "hsk_sub_id"), name="hsk_id_sub_id"),
        ),
    ]
