# Generated by Django 3.0.8 on 2020-07-05 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_squashed_0023_auto_20200116_1539"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SourceText",
        ),
    ]
