# Generated by Django 3.1.1 on 2020-09-13 02:43
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_delete_sourcetext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "status",
                    models.IntegerField(choices=[(0, "Inactive"), (1, "Active")], default=1, verbose_name="status"),
                ),
                (
                    "activate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for an immediate activation", null=True),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for indefinite activation", null=True),
                ),
            ],
            options={
                "ordering": ("status", "-activate_date"),
                "abstract": False,
            },
        ),
    ]
