# Generated by Django 3.1.1 on 2020-09-13 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_survey"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey", name="survey_json", field=models.JSONField(default=""), preserve_default=False,
        ),
    ]
