# Generated by Django 3.1.1 on 2020-09-13 02:48
import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_survey_survey_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="title", verbose_name="slug"
            ),
        ),
    ]
