# Generated by Django 3.1.1 on 2020-09-15 11:45
import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0005_survey_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSurvey",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("data", models.JSONField()),
                ("survey", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.survey")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"get_latest_by": "modified", "abstract": False},
        ),
    ]
