# Generated by Django 3.1.1 on 2020-09-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0007_survey_users"),
    ]

    operations = [
        migrations.AlterField(model_name="usersurvey", name="data", field=models.JSONField(null=True),),
    ]
