# Generated by Django 3.1.1 on 2020-09-16 02:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0008_auto_20200916_0002"),
    ]

    operations = [
        migrations.AlterModelOptions(name="usersurvey", options={},),
        migrations.AlterUniqueTogether(name="usersurvey", unique_together={("user", "survey")},),
    ]
