# Generated by Django 3.1.1 on 2020-10-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0009_auto_20200916_0251"),
    ]

    operations = [
        migrations.AddField(model_name="survey", name="is_obligatory", field=models.BooleanField(default=False),),
    ]
