# Generated by Django 3.1.2 on 2020-10-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0010_survey_is_obligatory"),
    ]

    operations = [
        migrations.RunSQL(
            (
                r"""
                    CREATE OR REPLACE FUNCTION simplified(fields text) RETURNS TEXT as
                    $$
                    /* This function extracts just the simplified characters from
                     * Anki notes 'flds' column formatted text. It will also strip
                     * any html, included that has been encoded with &lt; and &gt;
                     */
                      BEGIN
                        RETURN regexp_replace(
                                regexp_replace(
                                    replace(
                                        replace(substring(fields from 0 for position(chr(31) in fields)),
                                            '&gt;', '>'),
                                        '&lt;', '<'),
                                    E'(?x)<[^>]*?(\s alt \s* = \s* ([\'"]) ([^>]*?) \2) [^>]*? >', E'\3'),
                                E'(?x)(< [^>]*? >)', '', 'g');
                      END;
                    $$
                    LANGUAGE PLPGSQL IMMUTABLE; COMMIT;
                """
            )
        )
    ]
