# Generated by Django 3.1.2 on 2020-10-20 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0010_auto_20200110_0254"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0011_auto_20201005_1455"),
    ]

    operations = [
        migrations.AddField(
            model_name="userword",
            name="last_translated",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="userword",
            name="nb_translated",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="UserSentence",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nb_seen", models.IntegerField(default=0)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("nb_seen_since_last_check", models.IntegerField(default=0)),
                ("nb_translated", models.IntegerField(default=0)),
                ("last_translated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sentence",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enrich.bingapitranslation"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
