# Generated by Django 3.1.3 on 2020-11-28 07:13

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0012_auto_20201020_0926"),
    ]

    operations = [
        migrations.CreateModel(
            name="Import",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name="modified"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="description")),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title", verbose_name="slug"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(choices=[(0, "Inactive"), (1, "Active")], default=1, verbose_name="status"),
                ),
                (
                    "activate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for an immediate activation", null=True),
                ),
                (
                    "deactivate_date",
                    models.DateTimeField(blank=True, help_text="keep empty for indefinite activation", null=True),
                ),
                ("import_file", models.FileField(upload_to="imports/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterModelOptions(
            name="survey",
            options={},
        ),
    ]
