# Generated by Django 3.1.3 on 2020-11-28 07:35

import upload_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0013_auto_20201128_0713"),
    ]

    operations = [
        migrations.AddField(
            model_name="import",
            name="processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="import",
            name="import_file",
            field=models.FileField(
                upload_to="imports/",
                validators=[upload_validator.FileTypeValidator(allowed_types=["text/plain", "text/csv"])],
            ),
        ),
    ]
