# Generated by Django 3.1.3 on 2020-11-28 08:20

import django.core.validators
import django.db.models.deletion
import upload_validator
from django.conf import settings
from django.db import migrations, models

import data.models
import data.validators
import ndutils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0014_auto_20201128_0735"),
    ]

    operations = [
        migrations.AddField(
            model_name="import",
            name="user",
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to="auth.user"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="import",
            name="import_file",
            field=models.FileField(
                upload_to=ndutils.user_imports_path,
                validators=[
                    upload_validator.FileTypeValidator(allowed_types=["text/plain", "text/csv", "application/csv"]),
                    django.core.validators.FileExtensionValidator(allowed_extensions=["txt", "csv"]),
                    data.validators.validate_file_size,
                ],
            ),
        ),
    ]
