# Generated by Django 3.1.3 on 2020-11-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0015_auto_20201128_0820"),
    ]

    operations = [
        migrations.AddField(
            model_name="import",
            name="process_type",
            field=models.IntegerField(
                choices=[(1, "Vocabulary Only"), (2, "Grammar Only"), (3, "Vocabulary and Grammar")], default=1
            ),
        ),
    ]
