# Generated by Django 3.1.4 on 2020-12-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0017_auto_20201129_0526"),
    ]

    operations = [
        migrations.AddField(
            model_name="import",
            name="analysis",
            field=models.TextField(null=True),
        ),
    ]
