# Generated by Django 3.1.4 on 2020-12-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0019_goal_userlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="shared",
            field=models.BooleanField(default=False),
        ),
    ]
