# Generated by Django 3.1.4 on 2020-12-11 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrich", "0010_auto_20200110_0254"),
        ("data", "0020_userlist_shared"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserListWord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_list", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.userlist")),
                ("word", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enrich.bingapilookup")),
            ],
        ),
        migrations.CreateModel(
            name="UserListGrammarRule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grammar_rule", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.grammarrule")),
                ("user_list", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="data.userlist")),
            ],
        ),
    ]
