# Generated by Django 3.1.4 on 2020-12-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0021_userlistgrammarrule_userlistword"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="userlistgrammarrule",
            constraint=models.UniqueConstraint(fields=("user_list", "grammar_rule"), name="user_list_rule"),
        ),
        migrations.AddConstraint(
            model_name="userlistword",
            constraint=models.UniqueConstraint(fields=("user_list", "word"), name="user_list_word"),
        ),
    ]
