# Generated by Django 3.1.4 on 2020-12-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0023_auto_20201211_0236"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlist",
            name="order_by",
            field=models.IntegerField(choices=[(0, "Absolute Frequency"), (1, "Frequency in import")], default=0),
        ),
    ]
