# Generated by Django 3.1.4 on 2020-12-17 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0024_userlist_order_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="priority",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goal",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="data.goal",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="user_list",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="data.userlist"
            ),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="add_notes",
            field=models.BooleanField(default=False, help_text="Should Anki notes be added for each word?"),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="minimum_abs_frequency",
            field=models.IntegerField(
                default=-1,
                help_text="Minimum frequency in words per million, see the documentation for more details, -1 for all",
            ),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="minimum_doc_frequency",
            field=models.IntegerField(
                default=-1,
                help_text="Min occurrences in the import before the word will be added to the list, -1 for all",
            ),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="nb_to_take",
            field=models.IntegerField(default=-1, help_text="Maximum number of words in the list, -1 for all"),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="notes_are_known",
            field=models.BooleanField(default=False, help_text="Should the notes added be set to already known?"),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="only_dictionary_words",
            field=models.BooleanField(default=True, help_text="Ignore words that don't appear in the main dictionary"),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="order_by",
            field=models.IntegerField(
                choices=[(0, "Absolute Frequency"), (1, "Frequency in import")],
                default=0,
                help_text="Order of the words (only useful when a maximum number is specified)",
            ),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="shared",
            field=models.BooleanField(default=False, help_text="Allow others to see and use this list?"),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="the_import",
            field=models.ForeignKey(
                help_text="The import to create the list from",
                on_delete=django.db.models.deletion.CASCADE,
                to="data.import",
            ),
        ),
    ]
