# Generated by Django 3.1.4 on 2020-12-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0025_auto_20201217_2344"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="priority",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)], default=5
            ),
        ),
    ]
