# Generated by Django 3.1.4 on 2020-12-24 01:02

import django.core.validators
import django.db.models.deletion
import upload_validator
from django.conf import settings
from django.db import migrations, models

import data.models
import data.validators
import ndutils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0028_import_shared"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="import_file",
            field=models.FileField(
                help_text="File to import",
                upload_to=ndutils.user_imports_path,
                validators=[
                    upload_validator.FileTypeValidator(allowed_types=["text/plain", "text/csv", "application/csv"]),
                    django.core.validators.FileExtensionValidator(allowed_extensions=["txt", "csv"]),
                    data.validators.validate_file_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="import",
            name="process_type",
            field=models.IntegerField(
                choices=[(1, "Vocabulary Only"), (2, "Grammar Only"), (3, "Vocabulary and Grammar")],
                default=1,
                help_text="What items to extract",
            ),
        ),
        migrations.AlterField(
            model_name="import",
            name="processed",
            field=models.BooleanField(default=False, help_text="Import status", null=True),
        ),
        migrations.AlterField(
            model_name="import",
            name="user",
            field=models.ForeignKey(
                help_text="Import owner", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
