# Generated by Django 3.1.5 on 2021-01-11 23:27

import django.core.validators
import upload_validator
from django.db import migrations, models

import data.validators
import ndutils


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0029_auto_20201224_0102"),
    ]

    operations = [
        migrations.AlterField(
            model_name="import",
            name="import_file",
            field=models.FileField(
                help_text="File to import",
                upload_to=ndutils.user_imports_path,
                validators=[
                    upload_validator.FileTypeValidator(
                        allowed_types=["text/plain", "text/csv", "application/csv", "application/zip"]
                    ),
                    django.core.validators.FileExtensionValidator(allowed_extensions=["txt", "csv", "epub"]),
                    data.validators.validate_file_size,
                ],
            ),
        ),
    ]
