# Generated by Django 3.1.6 on 2021-02-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0034_auto_20210214_0154"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="processed",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Requested"), (2, "Processing"), (3, "Finished"), (4, "ERROR")],
                default=0,
                help_text="Processed status",
            ),
        ),
        migrations.AlterField(
            model_name="import",
            name="processed",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Requested"), (2, "Processing"), (3, "Finished"), (4, "ERROR")],
                default=0,
                help_text="Processing status",
            ),
        ),
    ]
