# Generated by Django 3.1.6 on 2021-02-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0035_auto_20210215_0034"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="processed",
            new_name="processing",
        ),
        migrations.RenameField(
            model_name="import",
            old_name="processed",
            new_name="processing",
        ),
        migrations.AddField(
            model_name="content",
            name="shared",
            field=models.BooleanField(default=False, help_text="Allow others to see and use this content?"),
        ),
    ]
