# Generated by Django 3.1.6 on 2021-02-15 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0037_auto_20210215_0051"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userlist",
            old_name="processed",
            new_name="processing",
        ),
    ]
