# Generated by Django 3.1.7 on 2021-02-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0039_todo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
