# Generated by Django 3.1.7 on 2021-02-26 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0040_auto_20210226_0218"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
