# Generated by Django 3.1.7 on 2021-03-02 06:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("data", "0041_auto_20210226_0220"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transcrober",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "user"), ("manager", "manager")], default="user", max_length=120
                    ),
                ),
                ("from_lang", models.CharField(default="zh-Hans", max_length=20)),
                ("to_lang", models.CharField(default="en", max_length=20)),
                ("dictionary_ordering", models.CharField(default="mst,ccc,fbk", max_length=50)),
                ("default_segment", models.BooleanField(default=True, help_text="Segment texts by default")),
                (
                    "default_glossing",
                    models.IntegerField(
                        choices=[
                            (0, "Unmodified text"),
                            (4, "Simpler words"),
                            (6, "Transliteration"),
                            (8, "Native language"),
                        ],
                        default=8,
                        help_text="Default gloss mode for platform-internal reading",
                    ),
                ),
                (
                    "reading_mode",
                    models.CharField(
                        choices=[
                            ("dark", "Dark mode"),
                            ("light", "Light mode"),
                            ("white", "White mode"),
                            ("black", "Black mode"),
                        ],
                        default="dark",
                        help_text="Reading mode for platform-internal reading",
                        max_length=100,
                    ),
                ),
                (
                    "font_size_percent",
                    models.IntegerField(
                        default=100,
                        help_text="Default font size percent",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(200),
                        ],
                    ),
                ),
                (
                    "subtitle_default_segment",
                    models.BooleanField(default=True, help_text="Segment subtitles by default"),
                ),
                (
                    "subtitle_default_glossing",
                    models.IntegerField(
                        choices=[
                            (0, "Unmodified text"),
                            (4, "Simpler words"),
                            (6, "Transliteration"),
                            (8, "Native language"),
                        ],
                        default=8,
                        help_text="Default gloss mode for platform-internal subtitles",
                    ),
                ),
                (
                    "media_mode",
                    models.CharField(
                        choices=[
                            ("dark", "Dark mode"),
                            ("light", "Light mode"),
                            ("white", "White mode"),
                            ("black", "Black mode"),
                        ],
                        default="dark",
                        help_text="Video mode for platform-internal subtitles",
                        max_length=100,
                    ),
                ),
                (
                    "subtitle_box_width_percent",
                    models.IntegerField(
                        default=50,
                        help_text="Default subtitle box width percent",
                        validators=[
                            django.core.validators.MinValueValidator(25),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "subtitle_font_size_percent",
                    models.IntegerField(
                        default=150,
                        help_text="Default subtitle font size percent",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(250),
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userlist",
            name="add_notes",
        ),
        migrations.RemoveField(
            model_name="userlist",
            name="notes_are_known",
        ),
        migrations.AddField(
            model_name="userlist",
            name="add_cards",
            field=models.BooleanField(default=False, help_text="Should revision cards be added for each word?"),
        ),
        migrations.AddField(
            model_name="userlist",
            name="words_are_known",
            field=models.BooleanField(default=False, help_text="Should the words added be set to already known?"),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="the_import",
            field=models.ForeignKey(
                help_text="The import to create the list from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.import",
            ),
        ),
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
