# Generated by Django 3.1.7 on 2021-03-04 02:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enrich", "0012_auto_20201226_0316"),
        ("data", "0043_remove_transcrober_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "card_type",
                    models.IntegerField(
                        choices=[(1, "L2 written form"), (2, "L2 sound form"), (3, "L1 definition")],
                        default=1,
                        help_text="Card type",
                    ),
                ),
                ("interval", models.IntegerField(default=0, help_text="SM2 interval")),
                ("repetition", models.IntegerField(default=0, help_text="SM2 repetition")),
                ("efactor", models.IntegerField(default=2.5, help_text="SM2 efactor")),
                ("front", models.TextField(help_text="Override default definition cue", null=True)),
                ("back", models.TextField(help_text="Override default definition expected response", null=True)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("deleted", models.BooleanField(default=False, help_text="Card has been deleted")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
                ("word", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="enrich.bingapilookup")),
            ],
        ),
    ]
