# Generated by Django 3.1.7 on 2021-03-04 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("enrich", "0012_auto_20201226_0316"),
        ("data", "0045_auto_20210304_0529"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                help_text="Card owner", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="word",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="enrich.bingapilookup"),
        ),
    ]
