# Generated by Django 3.1.7 on 2021-03-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0046_auto_20210304_0537"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="due_date",
            field=models.DateTimeField(null=True),
        ),
    ]
