# Generated by Django 3.1.7 on 2021-03-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0047_card_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="is_known",
            field=models.BooleanField(default=False, help_text="Learner believes they 'know' the word/cardtype"),
        ),
    ]
