# Generated by Django 3.1.7 on 2021-03-12 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0048_card_is_known"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="is_known",
            new_name="known",
        ),
        migrations.AddField(
            model_name="card",
            name="suspended",
            field=models.BooleanField(default=False, help_text="Learner believes they 'know' the word/cardtype"),
        ),
    ]
