# Generated by Django 3.1.7 on 2021-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0049_auto_20210312_0604"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlistword",
            name="default_order",
            field=models.IntegerField(default=0),
        ),
    ]
