# Generated by Django 3.1.7 on 2021-03-22 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0051_auto_20210318_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="userword",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
