# Generated by Django 3.1.7 on 2021-03-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0053_remove_userlist_add_cards"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="card_type",
            field=models.IntegerField(
                choices=[(1, "L2 written form"), (2, "L2 sound form"), (3, "L1 meaning")],
                default=1,
                help_text="Card type",
            ),
        ),
        migrations.AlterField(
            model_name="import",
            name="processing",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Requested"), (2, "Processing"), (3, "Finished"), (4, "ERROR")],
                default=1,
                help_text="Processing status",
            ),
        ),
        migrations.AlterField(
            model_name="userlist",
            name="processing",
            field=models.IntegerField(
                choices=[(0, "None"), (1, "Requested"), (2, "Processing"), (3, "Finished"), (4, "ERROR")],
                default=1,
                help_text="Processed status",
            ),
        ),
    ]
