# Generated by Django 3.1.7 on 2021-03-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0054_auto_20210327_1342"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="first_revision_date",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="suspended",
            field=models.BooleanField(default=False, help_text="Don't revise the cardtype"),
        ),
    ]
