# Generated by Django 3.1.7 on 2021-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0055_auto_20210328_0051"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="last_revision_date",
            field=models.DateTimeField(null=True),
        ),
    ]
