# vim:set ft=dockerfile:
FROM registry.gitlab.com/transcrobes/transcrobes/tc_pyaudio:v0.0.2

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY requirements.txt /app

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
